# Generated by Django 2.1.5 on 2019-01-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='rating_critics',
        ),
    ]
