# Generated by Django 2.1.5 on 2019-01-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_remove_author_rating_critics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Suspense', 'Suspense'), ('Horror', 'Horror'), ('Fiction', 'Fiction')], max_length=50),
        ),
    ]
